<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXmonvng\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXmonvng/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXmonvng.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXmonvng\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXmonvng\appProdProjectContainer([
    'container.build_hash' => 'Xmonvng',
    'container.build_id' => '06a30381',
    'container.build_time' => 1634242407,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXmonvng');
